import Head from "next/head";
import ComLog from "../Components/ComLog";
import Enrollments from "../Components/Enrollments";
import UserDetails from "../Components/UserDetails";

export default function Home() {
  return (
    <>
      <Head>
        <title>PVS0000 Student Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UserDetails />
      <div className="row">
        <div className="col-xl-4 col-lg-5 scrollbar scrollbar-primary">
          <ComLog />
        </div>
        <div className="col-xl-8 col-lg-7">
          <Enrollments />
        </div>
      </div>
    </>
  );
}
